server {
    listen 127.0.0.1:4432 ssl;
    ssl_certificate "/etc/nginx/example/fullchain.cer";
    ssl_certificate_key "/etc/nginx/example/cerkey.key";
    ssl_protocols TLSv1.3 TLSv1.2;
    server_name alist.example.com;

  location / {
    proxy_pass http://127.0.0.1:20010;
  }
}

server {
    listen 127.0.0.1:4432 ssl;
    ssl_certificate "/etc/nginx/example/fullchain.cer";
    ssl_certificate_key "/etc/nginx/example/cerkey.key";
    ssl_protocols TLSv1.3 TLSv1.2;
    server_name emby.example.com;

      location / {
        proxy_pass http://127.0.0.1:20011;
      }
}